// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqOYbZFpnFhKdPztFkE5XfRmq0qMD2R9g',
    appId: '1:178481495064:web:edc9b3b59bd782ea05176d',
    messagingSenderId: '178481495064',
    projectId: 'reacsa-10ffe',
    authDomain: 'reacsa-10ffe.firebaseapp.com',
    storageBucket: 'reacsa-10ffe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgXT-z38RUsmZC4setTNMGz3pBSM6i7fY',
    appId: '1:178481495064:android:6fe9ea1e1e1b85bf05176d',
    messagingSenderId: '178481495064',
    projectId: 'reacsa-10ffe',
    storageBucket: 'reacsa-10ffe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBE9D6moZhS8MXk9AUfKKlvY7phVDXuDxg',
    appId: '1:178481495064:ios:4713e3768a16432d05176d',
    messagingSenderId: '178481495064',
    projectId: 'reacsa-10ffe',
    storageBucket: 'reacsa-10ffe.appspot.com',
    iosClientId: '178481495064-158ob623rlcffvfg9qkanj17bvkcnhng.apps.googleusercontent.com',
    iosBundleId: 'com.example.recasa',
  );
}
